export const APP__SET_LOADING = 'APP__SET_LOADING';

//Auth
export const SET_AUTH_LOADER = 'SET_AUTH_LOADER';
export const UPDATE_LOGIN_USER = 'UPDATE_LOGIN_USER';
export const CLEAR_LOGIN_USER = 'CLEAR_LOGIN_USER';

//User
export const SET_USER_LOADER = 'SET_USER_LOADER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_INFO = 'SET_USER_INFO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO';
export const SET_LANGUAGE_LIST = 'SET_LANGUAGE_LIST';
export const SET_USER_STATUS_LIST = 'SET_USER_STATUS_LIST';
export const SET_USER_SOCIAL_LIST = 'SET_USER_SOCIAL_LIST';
export const SET_APP_DETAIL = 'SET_APP_DETAIL';
export const SET_CONTACT_TYPE_LIST = 'SET_CONTACT_TYPE_LIST';
export const SET_COUNTRY_LIST = 'SET_COUNTRY_LIST';
export const SET_UPSELL_CARD = 'SET_UPSELL_CARD';
export const SET_POPUP_LIST = 'SET_POPUP_LIST';
export const SET_FAQ = 'SET_FAQ';
export const SET_USER_FEEDBACK_LIST = 'SET_USER_FEEDBACK_LIST';
export const UPDATE_USER_FEEDBACK_LIST_ITEM = 'UPDATE_USER_FEEDBACK_LIST_ITEM';
export const CLEAR_USER_FEEDBACK_LIST = 'CLEAR_USER_FEEDBACK_LIST';

//Plan
export const SET_PLAN_LOADER = 'SET_PLAN_LOADER';
export const SET_PLAN_LIST = 'SET_PLAN_LIST';
export const SET_QUESTION_ACTIVITY_DONE = 'SET_QUESTION_ACTIVITY_DONE';
export const SET_ACTIVITY_REPORT_DATA = 'SET_ACTIVITY_REPORT_DATA';
export const SET_BACKUP_CLASS_DATA = 'SET_BACKUP_CLASS_DATA';
export const SET_SELECTED_PLAN = 'SET_SELECTED_PLAN';
export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';

//Order
export const SET_ORDER_LOADER = 'SET_ORDER_LOADER';
export const SET_ORDER_LIST = 'SET_ORDER_LIST';
export const SET_ORDER_DETAIL = 'SET_ORDER_DETAIL';
export const SET_PAYMENT_STRUCTURE = 'SET_PAYMENT_STRUCTURE';
export const SET_ADDRESS_LIST = 'SET_ADDRESS_LIST';
export const SET_ADDRESS = 'SET_ADDRESS';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const CLEAR_ADDRESS = 'CLEAR_ADDRESS';
export const SET_ORDER_SUMMARY = 'SET_ORDER_SUMMARY';
export const SET_NEW_ORDER = 'SET_NEW_ORDER';
export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';

//Notification
export const SET_NOTIFICATION_LOADER = 'SET_NOTIFICATION_LOADER';
export const SET_NOTIFICATION_LIST = 'SET_NOTIFICATION_LIST';
export const UPDATE_NOTIFICATION_ITEM = 'UPDATE_NOTIFICATION_ITEM';
