import { WIN_HEIGHT } from '@app/constants/constant';
import { colors, fontWeights } from '@app/styles';
import { doubleIndent, halfindent, indent, lessIndent } from '@app/styles/dimensions';
import { scale, scaleVertical } from '@app/utils/scale';
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  maincontain: {
    backgroundColor: colors.white,
  },
  headernotiRow: {
    paddingHorizontal: indent,
  },
  headerText: {
    color: colors.black,
    fontWeight: fontWeights.extraBold,
  },
  addIcon: {
    marginLeft: halfindent,
  },
  root: {
    backgroundColor: colors.white,
    flex: 1,
    paddingVertical: doubleIndent - 2,
    paddingHorizontal: indent,
  },
  bggraphics: {
    width: 180,
    height: 180,
    borderRadius: 100,
    backgroundColor: colors.bgpink,
    alignSelf: 'center',
    overflow: 'hidden',
  },
  imgscreen: {
    width: 180,
    height: 180,
  },
  activityCard: {
    width: '100%',
    marginTop: doubleIndent - 2,
  },
  card: {
    backgroundColor: colors.bglightpurple,
    borderRadius: 12,
    position: 'relative',
    flexDirection: 'row',
    overflow: 'hidden',
    paddingBottom: lessIndent,
  },
  secondimg: {
    position: 'absolute',
    width: '100%',
    top: 0,
    left: 0,
    bottom: 0,
  },
  textview: {
    marginVertical: indent + halfindent - 4,
    marginLeft: indent + halfindent - 4,
    width: scale(150),
    textAlign: 'left',
  },
  blacktext: {
    color: colors.black,
    fontWeight: fontWeights.extraBold,
    textAlign: 'left',
  },
  duration: {
    color: colors.dimGray,
    fontSize: 13,
    fontWeight: fontWeights.medium,
    marginVertical: halfindent,
  },
  duratintext: {
    color: colors.dimGray,
    fontWeight: fontWeights.medium,
  },
  whitecard: {
    width: scale(128),
    height: scaleVertical(WIN_HEIGHT / 7.3),
    marginLeft: halfindent,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    backgroundColor: colors.bgcard,
    shadowColor: colors.prizeShadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  },
  prizecard: {
    paddingTop: indent + halfindent - 4,
    paddingHorizontal: doubleIndent + 2,
    backgroundColor: colors.white,
    paddingBottom: halfindent + 2,
  },
  mrp: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    textDecorationLine: 'line-through',
  },
  prize: {
    fontSize: 23,
    lineHeight: 28,
    fontWeight: 'bold',
    color: colors.primary,
    textAlign: 'center',
  },
  gst: {
    fontSize: 8,
    textAlign: 'right',
    color: colors.primary,
  },
  fram: {
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  btmview: {
    paddingVertical: lessIndent - 2,
  },
  discount: {
    color: colors.primary,
    textAlign: 'center',
    fontWeight: fontWeights.bold,
  },
  secondCard: {
    backgroundColor: colors.bgyellow,
    borderRadius: 12,
    flexDirection: 'row',
    overflow: 'hidden',
    marginTop: indent,
    position: 'relative',
  },
  secdimg: {
    width: scale(78),
    height: scaleVertical(95),
    marginTop: halfindent,
  },
  freetag: {
    width: 30,
    height: 30,
    position: 'absolute',
    right: 0,
    top: 5,
  },
  righticon: {
    marginTop: 1,
  },
  sectext: {
    paddingVertical: indent,
    marginLeft: indent - 1,
  },
  btn: {
    backgroundColor: colors.yellow,
    paddingVertical: halfindent - 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    width: 115,
    marginTop: halfindent - 1,
  },
  btntext: {
    color: colors.white,
    fontWeight: fontWeights.semiBold,
    marginRight: halfindent - 2,
  },
  btnicon: {
    marginTop: 1,
  },
  checkview: {
    alignSelf: 'center',
    marginTop: halfindent,
    width: 321,
  },
  checklist: {
    flexDirection: 'row',
    marginTop: indent,
  },
  listtext: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    marginLeft: halfindent - 2,
  },
  ourCard: {
    width: '100%',
    marginTop: 50,
  },
  ourView: {
    backgroundColor: colors.bglightgreen,
    borderRadius: 12,
    position: 'relative',
    flexDirection: 'row',
    paddingVertical: indent + halfindent,
    paddingHorizontal: indent,
    width: '100%',
  },
  righttop: {
    position: 'absolute',
    width: '100%',
    top: -39,
    right: 0,
    bottom: 0,
  },
  ourVision: {
    width: '100%',
    maxWidth: '50%',
  },
  visionText: {
    color: colors.black,
    fontWeight: fontWeights.medium,
    marginLeft: 3,
  },
  midText: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    marginTop: indent - 4,
  },
  happyText: {
    marginTop: halfindent,
    color: colors.dimGray,
  },
  ourMission: {
    width: '100%',
    maxWidth: '50%',
    paddingLeft: indent,
  },
  userView: {
    marginTop: 50,
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: -16,
  },
  users: {
    alignSelf: 'center',
    alignItems: 'center',
    width: '100%',
    maxWidth: '33.33%',
    paddingHorizontal: halfindent,
    marginBottom: indent,
  },
  firstbg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.darkgreen,
  },
  secondbg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.skyblue,
  },
  thirdbg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.litered,
  },
  fourbg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.darkpurple,
  },
  fivebg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.pink,
  },
  sixbg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.lowyellow,
  },
  userss: {
    alignSelf: 'center',
    alignItems: 'center',
    width: '100%',
    maxWidth: '33.33%',
    paddingHorizontal: 10,
    marginBottom: indent,
    backgroundColor: colors.pelorous,
  },
  boldtext: {
    color: colors.dimGray,
    textAlign: 'center',
    fontWeight: fontWeights.extraBold,
    marginTop: halfindent + 2,
  },
  captionicon: {
    color: colors.dimGray,
    textAlign: 'center',
    marginTop: halfindent / 2,
  },
  founderSection: {
    width: '100%',
    marginTop: 50,
    height: scaleVertical(168),
  },
  imgview: {
    backgroundColor: colors.bglightcream,
    borderRadius: 12,
    position: 'relative',
    height: '100%',
  },
  fondimg: {
    position: 'absolute',
    width: '100%',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  textcontain: {
    width: scale(192),
    marginVertical: scaleVertical(38),
    marginRight: halfindent,
    marginLeft: 'auto',
  },
  talktext: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    marginTop: 10,
  },
  reviewSection: {
    marginTop: 50,
    height: 236,
  },
  allreview: {
    position: 'relative',
    height: '100%',
  },
  centerview: {
    width: '100%',
    maxWidth: 284,
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 34,
  },
  reviewtext: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    marginTop: halfindent,
    textAlign: 'center',
    lineHeight: 19,
  },
  clientname: {
    fontWeight: fontWeights.extraBold,
    color: colors.dimGray,
    marginTop: halfindent - 2,
  },
  btnview: {
    marginTop: indent + halfindent - 3,
    paddingHorizontal: indent,
    marginBottom: indent + halfindent,
  },
  btntextmain: {
    color: colors.white,
    fontWeight: fontWeights.semiBold,
    marginRight: halfindent - 2,
  },
  btnplan: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: indent,
    borderRadius: 8,
    backgroundColor: colors.primary,
  },
  chartMain: {
    backgroundColor: colors.white,
    borderRadius: 12,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  paddingView: {
    paddingVertical: indent + 4,
    paddingHorizontal: indent,
  },
  chartHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: indent,
  },
  btnRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginBottom: indent,
  },
  textHead: {
    color: colors.black,
    fontWeight: fontWeights.extraBold,
  },
  inacText: {
    color: colors.dimGray,
    fontWeight: fontWeights.semiBold,
    opacity: 0.4,
    fontFamily: 'Roboto-Regular',
  },
  actiText: {
    color: colors.white,
    fontWeight: fontWeights.semiBold,
    fontFamily: 'Roboto-Regular',
  },
  inactiveTab: {
    paddingHorizontal: lessIndent - 1,
    paddingVertical: 5,
    marginRight: 4,
  },
  activeTab: {
    paddingHorizontal: lessIndent - 1,
    paddingVertical: 5,
    backgroundColor: colors.primary,
    borderRadius: 4,
    marginRight: 4,
    color: colors.white,
  },
  leftTab: {
    paddingLeft: indent,
  },
  cardlist: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    margin: -8,
  },
  spacelist: {
    width: '100%',
    maxWidth: '50%',
    minWidth: '50%',
    flex: 1,
    padding: halfindent,
  },
  cardItem: {
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    paddingBottom: 12,
    paddingTop: 6,
  },
  yogimg: {
    width: 60,
    height: 60,
  },
  textTitle: {
    paddingLeft: halfindent - 4,
  },
  cardtext: {
    color: colors.dimGray,
    fontWeight: fontWeights.medium,
  },
  cardcaption: {
    color: colors.black,
    fontWeight: fontWeights.extraBold,
    marginTop: 5,
  },
});
