import { Platform, StyleSheet } from 'react-native';
import { WIN_HEIGHT, WIN_WIDTH } from '@app/constants/constant';
import { colors, fontWeights } from '@app/styles';
import { borderWidth, doubleIndent, halfindent, indent, lessIndent } from '@app/styles/dimensions';
import { scale, scaleVertical } from '@app/utils/scale';
import Typography from '@app/styles/Typography';

export default StyleSheet.create({
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headtext: {
    color: colors.black,
    fontWeight: fontWeights.extraBold,
  },
  ltext: {
    color: colors.dimGray,
    fontWeight: fontWeights.semiBold,
    marginRight: halfindent - 3,
  },
  dayview: {
    width: scale(24),
    height: scaleVertical(24),
    backgroundColor: colors.primary,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: halfindent,
  },
  daytext: {
    fontWeight: fontWeights.semiBold,
    color: colors.white,
  },
  maincontain: {
    backgroundColor: colors.white,
    flex: 1,
  },
  maincontainpadding: {
    backgroundColor: colors.white,
    flex: 1,
  },
  headerText: {
    color: colors.black,
    fontWeight: fontWeights.extraBold,
  },
  addIcon: {
    marginLeft: halfindent,
  },
  root: {
    backgroundColor: colors.white,
    flex: 1,
    paddingVertical: indent,
  },
  purchaseroot: {
    backgroundColor: colors.white,
    flex: 1,
    paddingVertical: indent,
    paddingHorizontal: indent,
  },
  bggraphics: {
    width: 180,
    height: 180,
    borderRadius: 100,
    backgroundColor: colors.bgpink,
    alignSelf: 'center',
    overflow: 'hidden',
    marginTop: 20,
  },
  imgscreen: {
    width: 180,
    height: 180,
  },
  activityCard: {
    width: '100%',
    marginTop: doubleIndent - 2,
    marginBottom: halfindent - 2,
  },
  card: {
    backgroundColor: colors.bglightpurple,
    borderRadius: 12,
    position: 'relative',
    overflow: 'hidden',
  },
  secondimg: {
    position: 'absolute',
    width: '100%',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  textview: {
    marginVertical: indent + halfindent - 4,
    marginHorizontal: indent + halfindent - 4,
    textAlign: 'left',
  },
  headTitle: {
    color: colors.black,
    fontWeight: fontWeights.extraBold,
    marginTop: indent + 4,
  },
  blacktext: {
    color: colors.black,
    fontWeight: fontWeights.extraBold,
    textAlign: 'left',
  },
  duration: {
    color: colors.dimGray,
    fontWeight: fontWeights.medium,
    marginTop: halfindent - 3,
    marginBottom: halfindent - 3,
  },
  classConvied: {
    color: colors.dimGray,
    marginBottom: halfindent,
  },
  duratintext: {
    color: colors.dimGray,
    fontWeight: fontWeights.medium,
  },
  whitecard: {
    width: scale(130),
    height: scaleVertical(WIN_HEIGHT / 7.3),
    marginLeft: halfindent,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    backgroundColor: colors.bgcard,
    shadowColor: colors.prizeShadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  },
  prizecard: {
    paddingTop: indent + halfindent - 4,
    paddingHorizontal: doubleIndent + halfindent - 1,
    backgroundColor: colors.white,
    paddingBottom: halfindent + 2,
  },
  mrp: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    textDecorationLine: 'line-through',
  },
  prize: {
    fontSize: 23,
    lineHeight: 28,
    fontWeight: 'bold',
    color: colors.primary,
    textAlign: 'center',
  },
  gst: {
    fontSize: 8,
    textAlign: 'right',
    color: colors.primary,
  },
  fram: {
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  btmview: {
    paddingVertical: lessIndent - 2,
  },
  discount: {
    color: colors.primary,
    textAlign: 'center',
    fontWeight: fontWeights.bold,
  },
  secondCard: {
    backgroundColor: colors.bgyellow,
    borderRadius: 12,
    flexDirection: 'row',
    overflow: 'hidden',
    marginTop: indent,
    position: 'relative',
    justifyContent: 'center',
  },
  secdimg: {
    // width: scale(78),
    // height: scaleVertical(95),
    marginTop: halfindent,
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  righticon: {
    marginTop: 1,
  },
  sectext: {
    paddingVertical: indent,
    marginLeft: 'auto',
    marginRight: doubleIndent,
  },
  btn: {
    backgroundColor: colors.yellow,
    paddingVertical: halfindent - 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    width: scale(100),
    marginTop: halfindent + 2,
  },
  btntext: {
    color: colors.white,
    fontWeight: fontWeights.semiBold,
    marginRight: halfindent - 2,
  },
  btnicon: {
    marginTop: 1,
  },
  checkview: {
    alignSelf: 'center',
    width: 321,
  },
  checklist: {
    flexDirection: 'row',
    marginTop: indent,
  },
  rowlist: {
    marginTop: indent,
    marginBottom: halfindent,
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: indent + halfindent,
  },
  row_list: {
    marginTop: indent,
    marginBottom: halfindent,
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: indent + halfindent,
    paddingHorizontal: indent,
  },
  weeklycontain: {
    marginTop: indent,
    marginBottom: indent + halfindent,
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: indent + halfindent,
  },
  smileicon: {
    marginRight: halfindent - 2,
  },
  listtext: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    marginLeft: halfindent - 2,
  },
  ourCard: {
    width: '100%',
    marginTop: 50,
  },
  ourView: {
    backgroundColor: colors.bglightgreen,
    borderRadius: 12,
    position: 'relative',
    flexDirection: 'row',
    paddingVertical: indent + halfindent,
    paddingHorizontal: indent,
    width: '100%',
  },
  righttop: {
    position: 'absolute',
    width: '100%',
    top: -39,
    right: 0,
    bottom: 0,
  },
  ourVision: {
    width: '100%',
    maxWidth: '50%',
  },
  visionText: {
    color: colors.black,
    fontWeight: fontWeights.medium,
    marginLeft: 3,
  },
  midText: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    marginTop: indent - 4,
  },
  happyText: {
    marginTop: halfindent,
    color: colors.dimGray,
  },
  ourMission: {
    width: '100%',
    maxWidth: '50%',
    paddingLeft: indent,
  },
  userView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -8,
    marginBottom: -8,
    marginTop: indent,
  },
  users: {
    width: '100%',
    maxWidth: '50%',
    minWidth: '50%',
    padding: 8,
  },
  FactView: {
    borderWidth: borderWidth,
    borderColor: colors.borderColor,
    borderRadius: 5,
    paddingVertical: halfindent + 2,
    paddingHorizontal: halfindent + 2,
    alignItems: 'center',
    flexDirection: 'row',
    flex: 1,
    width: '100%',
  },
  userstwo: {
    alignItems: 'center',
    width: '100%',
    maxWidth: '33.33%',
    paddingHorizontal: halfindent,
    marginBottom: indent,
  },
  firstbg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.darkgreen,
  },
  secondbg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.skyblue,
  },
  thirdbg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.litered,
  },
  fourbg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.darkpurple,
  },
  fivebg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.pink,
  },
  sixbg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.lowyellow,
  },
  userss: {
    alignSelf: 'center',
    alignItems: 'center',
    width: '100%',
    maxWidth: '33.33%',
    paddingHorizontal: 10,
    marginBottom: indent,
    backgroundColor: colors.pelorous,
  },
  boldtext: {
    color: colors.dimGray,
    textAlign: 'center',
    fontWeight: fontWeights.extraBold,
    marginTop: halfindent + 2,
  },
  factText: {
    marginLeft: halfindent + 2,
  },
  factTop: {
    color: colors.dimGray,
    fontWeight: fontWeights.extraBold,
  },
  captionicon: {
    color: colors.dimGray,
    textAlign: 'center',
    marginTop: halfindent,
  },
  captionfact: {
    color: colors.dimGray,
    marginTop: halfindent - 3,
  },
  founderSection: {
    width: '100%',
    marginTop: 50,
    height: scaleVertical(168),
    marginBottom: halfindent,
  },
  imgview: {
    backgroundColor: colors.bglightcream,
    borderRadius: 12,
    position: 'relative',
    height: '100%',
  },
  fondimg: {
    position: 'absolute',
    width: '100%',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  textcontain: {
    width: scale(192),
    marginVertical: scaleVertical(38),
    marginRight: halfindent,
    marginLeft: 'auto',
  },
  talktext: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    marginTop: 10,
  },
  reviewSection: {
    marginTop: 25,
    marginBottom: 20,
  },
  allreview: {
    position: 'relative',
  },
  centerview: {
    width: '100%',
    alignItems: 'center',
    alignSelf: 'center',
    paddingHorizontal: indent,
  },
  clientView: {
    marginTop: indent,
  },
  reviewtext: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    marginTop: halfindent,
    textAlign: 'center',
    lineHeight: 19,
  },
  clientname: {
    fontWeight: fontWeights.extraBold,
    color: colors.dimGray,
    marginTop: halfindent - 2,
    textAlign: 'center',
  },
  coutryname: {
    color: colors.dimGray,
    textAlign: 'center',
  },
  btnview: {
    marginTop: indent + halfindent - 3,
    paddingHorizontal: indent,
    marginBottom: indent + halfindent,
    backgroundColor: colors.white,
  },
  btntextmain: {
    color: colors.white,
    fontWeight: fontWeights.extraBold,
    marginRight: halfindent - 2,
  },
  btnplan: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: indent,
    borderRadius: 8,
    backgroundColor: colors.primary,
    flex: 0.5,
    marginRight: lessIndent,
    ...Platform.select({
      ios: {
        flexGrow: 1,
        paddingHorizontal: 30,
        flex: 0,
      },
    }),
  },
  //demo screen
  btnDemo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: indent,
    borderRadius: 8,
    flex: 0.5,
    marginRight: lessIndent,
    backgroundColor: colors.yellow,
    ...Platform.select({
      ios: {
        flexGrow: 1,
        paddingHorizontal: 30,
        flex: 0,
      },
    }),
  },
  democard: {
    backgroundColor: colors.bgsky,
    borderRadius: 10,
    padding: indent,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: halfindent,
  },
  imgCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: halfindent + 2,
    paddingVertical: halfindent - 1,
  },
  bagimg: {
    width: 60,
    height: 60,
  },
  kittext: {
    color: colors.dimGray,
    flexWrap: 'wrap',
  },
  lastcaption: {
    color: colors.dimGray,
    fontWeight: fontWeights.bold,
  },
  seccard: {
    // backgroundColor: colors.bgskylite,
    alignItems: 'center',
    marginLeft: 'auto',
    borderLeftWidth: 1,
    borderStyle: Platform.OS === 'ios' ? 'solid' : 'dashed',
    borderColor: colors.borderdash,
    paddingLeft: indent + 2,
    paddingRight: 2,
  },
  textcon: {
    width: scale(158),
    paddingLeft: indent,
  },
  expiretext: {
    color: colors.dimGray,
  },
  bgwhite: {
    width: 35,
    height: 35,
    backgroundColor: colors.white,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: halfindent / 2,
  },
  expday: {
    color: colors.dimGray,
  },
  boxview: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    margin: -8,
  },
  widthstyle: {
    alignSelf: 'center',
    alignItems: 'center',
    width: '100%',
    maxWidth: '50%',
    minWidth: '50%',
    padding: 8,
    flex: 1,
  },
  conbg: {
    alignSelf: 'center',
    alignItems: 'center',
    paddingVertical: indent - 4,
    borderRadius: 12,
    width: '100%',
    position: 'relative',
    backgroundColor: colors.bglightgreen,
  },
  imgfirstbox: {
    width: 52,
    height: 52,
  },
  weeksday: {
    fontSize: 8,
    textTransform: 'uppercase',
    marginTop: lessIndent,
  },
  demoboxtext: {
    fontWeight: fontWeights.extraBold,
    color: colors.dimGray,
  },
  boxtext: {
    fontWeight: fontWeights.extraBold,
    color: colors.dimGray,
    marginTop: halfindent / 2,
  },
  headingText: {
    marginBottom: indent,
    marginTop: doubleIndent,
  },
  fetures: {
    fontWeight: fontWeights.extraBold,
    color: colors.black,
  },
  conbgtwo: {
    alignSelf: 'center',
    alignItems: 'center',
    paddingVertical: indent - 4,
    backgroundColor: colors.bglightcream,
    borderRadius: 12,
    width: '100%',
    position: 'relative',
  },
  taj: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
  listspace: {
    marginTop: indent,
  },
  cardview: {
    borderWidth: borderWidth,
    borderColor: colors.borderColor,
    borderRadius: lessIndent,
    paddingVertical: halfindent - 2,
    paddingLeft: halfindent,
    marginBottom: indent,
    position: 'relative',
    overflow: 'hidden',
  },
  cardList: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  imgviewtwo: {
    width: scale(96),
    height: scaleVertical(65),
    borderRadius: 7,
  },
  textView: {
    marginLeft: indent,
    width: scale(217),
  },
  title: {
    color: colors.dimGray,
    fontWeight: fontWeights.medium,
    marginBottom: 5,
  },
  time: {
    color: colors.dimGray,
    fontWeight: fontWeights.medium,
    marginLeft: 5,
  },
  lockicon: {
    position: 'absolute',
    right: 10,
    top: 10,
  },
  counsellView: {
    backgroundColor: colors.bglightpurple,
    paddingLeft: indent,
    paddingRight: indent,
    paddingTop: lessIndent,
    borderRadius: 12,
    flexDirection: 'row',
  },
  callgirls: {
    width: 82,
    height: 94,
  },
  bagview: {
    backgroundColor: colors.bglightpurple,
    paddingVertical: indent - 1,
    paddingLeft: indent,
    paddingRight: indent,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconview2: {
    width: 30,
    height: 30,
    backgroundColor: colors.white,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
  },
  textcon2: {
    width: scale(175),
    marginLeft: indent + 4,
  },
  textgirls: {
    marginLeft: indent + 4,
  },
  kittext2: {
    color: colors.black,
    fontWeight: fontWeights.extraBold,
  },
  lastcaption2: {
    color: colors.dimGray,
    fontWeight: fontWeights.medium,
    marginTop: 5,
    width: 175,
  },
  lastcaps: {
    color: colors.dimGray,
    fontWeight: fontWeights.medium,
    marginTop: 5,
    width: 200,
  },
  //Backup card
  knowCard: {
    backgroundColor: colors.bgnotice,
    paddingVertical: indent,
    paddingHorizontal: indent + halfindent - 2,
    borderRadius: 10,
    marginTop: 10,
  },
  didknow: {
    color: colors.black,
    fontWeight: fontWeights.extraBold,
    textAlign: 'center',
  },
  didcaption: {
    color: colors.dimGray,
    lineHeight: 24,
    textAlign: 'center',
    marginTop: halfindent + 2,
  },
  numberText: {
    ...Typography.capsOne,
    color: colors.dimGray,
    fontWeight: fontWeights.extraBold,
  },
  lasttextView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lastText: {
    color: colors.dimGray,
    lineHeight: 24,
    textAlign: 'center',
  },
  selectBackup: {
    borderWidth: borderWidth,
    borderColor: colors.borderColor,
    marginBottom: indent - 2,
    backgroundColor: colors.bglitegray,
    padding: lessIndent,
    borderRadius: 10,
  },
  unseenBackup: {
    borderWidth: borderWidth,
    borderColor: colors.borderColor,
    marginBottom: indent - 2,
    backgroundColor: colors.white,
    padding: lessIndent,
    borderRadius: 10,
  },
  numview: {
    width: 42,
    height: 42,
    backgroundColor: colors.bgselectnum,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  twoWay: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginLeft: indent,
    flex: 1,
  },
  classStatusView: {
    backgroundColor: colors.bgselectnum,
    paddingVertical: 5,
    paddingHorizontal: indent,
    borderRadius: 23,
  },
  seengray: {
    color: colors.dimGray,
    fontWeight: fontWeights.medium,
  },
  UnseenText: {
    color: colors.primary,
    fontWeight: fontWeights.medium,
  },
  OpenText: {
    color: colors.textgreen,
    fontWeight: fontWeights.medium,
  },
  backupCard: {
    borderWidth: borderWidth,
    borderColor: colors.borderColor,
    marginBottom: indent - 2,
    backgroundColor: colors.white,
    padding: lessIndent,
    borderRadius: 10,
  },
  bgnumview: {
    width: 42,
    height: 42,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: borderWidth,
    borderColor: colors.borderColor,
  },
  numgraytext: {
    color: colors.dimGray,
    fontWeight: fontWeights.semiBold,
  },
  numtext: {
    color: colors.primary,
    fontWeight: fontWeights.semiBold,
  },
  whitedatacard: {
    borderWidth: 1.5,
    borderColor: colors.loadingBorder,
  },
  newcaptiontext: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    marginBottom: lessIndent,
  },
  linetext: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    textDecorationLine: 'underline',
  },
  btnhead: {
    paddingVertical: 4,
    paddingHorizontal: indent,
    borderRadius: 5,
    backgroundColor: colors.primary,
    marginRight: 5,
  },
  btnheadtext: {
    ...Typography.capsOne,
    color: colors.white,
    fontWeight: fontWeights.semiBold,
  },
  list: {
    paddingHorizontal: indent,
  },
  //card
  //card
  freeCardWrap: {
    backgroundColor: colors.bgyellow,
    borderRadius: 12,
    paddingRight: lessIndent,
    overflow: 'hidden',
    marginTop: halfindent - 2,
    marginBottom: halfindent - 2,
    paddingLeft: 10,
    paddingTop: 10,
  },
  freeCardWrapdemo: {
    backgroundColor: colors.bgyellow,
    borderRadius: 12,
    paddingRight: lessIndent,
    overflow: 'hidden',
    marginTop: indent,
    marginBottom: halfindent - 2,
    paddingLeft: 10,
    paddingTop: 10,
  },
  startNow: {
    backgroundColor: colors.yellow,
    flexDirection: 'row',
    alignItems: 'center',
    width: 100,
    justifyContent: 'center',
    borderRadius: 4,
    paddingVertical: halfindent - 2,
    marginTop: halfindent,
  },
  freeRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  freeImg: {
    width: 80,
    height: 120,
  },
  freelecImg: {
    width: 92,
    height: 120,
    marginBottom: -5,
  },
  textFreeWrap: {
    paddingLeft: halfindent,
    flexWrap: 'wrap',
  },
  freeTextHead: {
    color: colors.black,
    fontWeight: fontWeights.extraBold,
  },
  daycaps: {
    color: colors.dimGray,
    width: 200,
  },
  startBtn: {
    color: colors.white,
    fontWeight: fontWeights.extraBold,
  },
  iconRight: {
    marginTop: 2,
    marginLeft: 4,
  },
  tag: {
    position: 'absolute',
    width: 75,
    height: 26,
    bottom: 0,
    right: 0,
  },
  fullWork: {
    width: 100,
    height: 120,
  },
  demo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
    backgroundColor: colors.bglightcream,
    paddingVertical: 10,
    borderRadius: 8,
  },
  demoText: {
    color: colors.red,
    fontFamily: 'Roboto-Medium',
    fontWeight: fontWeights.extraBold,
  },
  purchasecard: {
    paddingHorizontal: indent,
  },
  footBtnRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: -lessIndent,
  },
  ModalPopup: {
    width: WIN_WIDTH - indent * 3,
    height: 'auto',
    backgroundColor: colors.white,
    borderRadius: 4,
  },
  footerBox: {
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
});
