export default {
  Splash: 'Splash',
  Login: 'Login',
  Signup: 'Signup',
  Welcome: 'Welcome',
  Onboarding: 'Onboarding',
  NavigationRoot: 'NavigationRoot',
  DashboardRoot: 'DashboardRoot',
  MoreRoot: 'MoreRoot',
  ReportRoot: 'ReportRoot',
  NotificationRoot: 'NotificationRoot',
  Notification: 'Notification',
  Report: 'Report',
  More: 'More',
  MyProfile: 'MyProfile',
  ForgotPassword: 'ForgotPassword',
  ResetPassword: 'ResetPassword',
  AddNumber: 'AddNumber',
  EnterOtp: 'EnterOtp',
  SelectLanguage: 'SelectLanguage',
  BasicInformations: 'BasicInformations',
  Dashboard: 'Dashboard',
  FolderView: 'FolderView',
  DailyActivity: 'DailyActivity',
  StartPregnancy: 'StartPregnancy',
  Demo: 'Demo',
  Physical: 'Physical(PQ)',
  Intellectual: 'Intellectual (IQ)',
  Emotional: 'Emotional (EQ)',
  Spiritual: 'Spiritual (SQ)',
  MediaFile: 'MediaFile',
  PdfDetails: 'PdfDetails',
  WorkShop: 'WorkShop',
  WorkShopPurchase: 'WorkShopPurchase',
  Class: 'Class',
  ClassPurchase: 'ClassPurchase',
  BackupClass: 'BackupClass',
  Annoncements: 'Annoncements',
  AboutUS: 'About US',
  ContactUS: 'Contact US',
  MyOrders: 'My Orders',
  OrderDetail: 'Order Detail',
  ChangeLanguage: 'Change Language',
  CounsellingAsk: 'Counselling Ask',
  PrivacyPolicy: 'Privacy Policy & TC',
  FAQ: 'FAQ',
  UpdateProfile: 'Update Profile',
  NotificationDetail: 'NotificationDetail',
  Payment: 'Payment',
  SelectAddress: 'Select Address',
  AddAddress: 'Add Address',
  OrderSummary: 'Order Summary',
  NewUpdate: 'NewUpdate',
  Cart: 'Cart',
  TermsCondition: 'TermsCondition',
  AddProduct: 'AddProduct',
  PaymentSuccess: 'PaymentSuccess',
  PremiumPlan: 'Premium Plan',
  DailyActivityPurchase: 'DailyActivityPurchase',
  UnderMaintenance: 'UnderMaintenance',
  PaymentMaintenance: 'PaymentMaintenance',
  ChatWithUs: 'ChatWithUs',
};
