import { WIN_HEIGHT, WIN_WIDTH } from '@app/constants/constant';
import { colors, fontWeights } from '@app/styles';
import { borderWidth, doubleIndent, halfindent, indent, lessIndent } from '@app/styles/dimensions';
import Typography from '@app/styles/Typography';
import { scale, scaleVertical } from '@app/utils/scale';
import { Platform, StyleSheet } from 'react-native';

export default StyleSheet.create({
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  maincontain: {
    backgroundColor: colors.white,
  },
  headerText: {
    color: colors.black,
    fontFamily: 'Roboto-Medium',
    fontWeight: fontWeights.extraBold,
  },
  addIcon: {
    marginLeft: halfindent,
  },
  root: {
    backgroundColor: colors.white,
    flex: 1,
    paddingVertical: doubleIndent - 2,
    paddingHorizontal: indent,
  },
  bggraphics: {
    width: 180,
    height: 180,
    borderRadius: 100,
    backgroundColor: colors.bgpink,
    alignSelf: 'center',
    overflow: 'hidden',
  },
  imgscreen: {
    width: 180,
    height: 180,
  },
  activityCard: {
    width: '100%',
    marginTop: doubleIndent - 2,
    marginBottom: lessIndent,
  },
  card: {
    backgroundColor: colors.bglightpurple,
    borderRadius: 12,
    position: 'relative',
    flexDirection: 'row',
    overflow: 'hidden',
    paddingBottom: lessIndent,
  },
  secondimg: {
    position: 'absolute',
    width: '100%',
    top: 0,
    left: 0,
    bottom: 0,
  },
  textview: {
    marginVertical: indent + halfindent - 4,
    marginHorizontal: indent + halfindent - 4,
    textAlign: 'left',
  },
  blacktext: {
    color: colors.black,
    fontWeight: fontWeights.extraBold,
    textAlign: 'left',
  },
  duration: {
    color: colors.dimGray,
    fontSize: 13,
    fontWeight: fontWeights.medium,
    marginVertical: halfindent,
  },
  duratintext: {
    color: colors.dimGray,
    fontWeight: fontWeights.medium,
  },
  whitecard: {
    width: scale(128),
    height: scaleVertical(WIN_HEIGHT / 7.3),
    marginLeft: halfindent,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    backgroundColor: colors.bgcard,
    shadowColor: colors.prizeShadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  },
  prizecard: {
    paddingTop: indent + halfindent - 4,
    paddingHorizontal: doubleIndent + 2,
    backgroundColor: colors.white,
    paddingBottom: halfindent + 2,
  },
  mrp: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    textDecorationLine: 'line-through',
  },
  prize: {
    fontSize: 23,
    lineHeight: 28,
    fontWeight: 'bold',
    color: colors.primary,
    textAlign: 'center',
  },
  gst: {
    fontSize: 8,
    textAlign: 'right',
    color: colors.primary,
  },
  fram: {
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  btmview: {
    paddingVertical: lessIndent - 2,
  },
  discount: {
    color: colors.primary,
    textAlign: 'center',
    fontWeight: fontWeights.bold,
  },
  secondCard: {
    backgroundColor: colors.bgyellow,
    borderRadius: 12,
    flexDirection: 'row',
    overflow: 'hidden',
    marginTop: indent,
    position: 'relative',
  },
  rowlist: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: indent,
  },
  secdimg: {
    width: scale(100),
    height: scaleVertical(105),
  },
  freetag: {
    width: 30,
    height: 30,
    position: 'absolute',
    right: 6,
    top: 6,
  },
  righticon: {
    marginTop: 1,
  },
  sectext: {
    marginLeft: indent - 1,
  },
  btn: {
    backgroundColor: colors.yellow,
    paddingVertical: halfindent - 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    width: 115,
    marginTop: halfindent - 1,
  },
  btntext: {
    color: colors.white,
    fontWeight: fontWeights.semiBold,
    marginRight: halfindent - 2,
  },
  btnicon: {
    marginTop: 1,
  },
  checkview: {
    alignSelf: 'center',
    marginTop: halfindent,
    width: 321,
  },
  checklist: {
    flexDirection: 'row',
    marginTop: indent,
  },
  listtext: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    marginLeft: halfindent - 2,
  },
  ourCard: {
    width: '100%',
    marginTop: 50,
  },
  ourView: {
    backgroundColor: colors.bglightgreen,
    borderRadius: 12,
    position: 'relative',
    flexDirection: 'row',
    paddingVertical: indent + halfindent,
    paddingHorizontal: indent,
    width: '100%',
  },
  righttop: {
    position: 'absolute',
    width: '100%',
    top: -39,
    right: 0,
    bottom: 0,
  },
  ourVision: {
    width: '100%',
    maxWidth: '50%',
  },
  visionText: {
    color: colors.black,
    fontWeight: fontWeights.medium,
    marginLeft: 3,
  },
  midText: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    marginTop: indent - 4,
  },
  happyText: {
    marginTop: halfindent,
    color: colors.dimGray,
  },
  ourMission: {
    width: '100%',
    maxWidth: '50%',
    paddingLeft: indent,
  },
  userView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -8,
    marginBottom: -8,
    marginTop: indent,
  },
  users: {
    width: '100%',
    maxWidth: '50%',
    minWidth: '50%',
    padding: 8,
  },
  firstbg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.darkgreen,
  },
  secondbg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.skyblue,
  },
  thirdbg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.litered,
  },
  fourbg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.darkpurple,
  },
  fivebg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.pink,
  },
  sixbg: {
    width: 52,
    height: 52,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.lowyellow,
  },
  userss: {
    alignSelf: 'center',
    alignItems: 'center',
    width: '100%',
    maxWidth: '33.33%',
    paddingHorizontal: 10,
    marginBottom: indent,
    backgroundColor: colors.pelorous,
  },
  boldtext: {
    color: colors.dimGray,
    textAlign: 'center',
    fontWeight: fontWeights.extraBold,
    marginTop: halfindent + 2,
  },
  captionicon: {
    color: colors.dimGray,
    textAlign: 'center',
    marginTop: halfindent / 2,
  },
  founderSection: {
    width: '100%',
    marginVertical: doubleIndent - 2,
    height: scaleVertical(168),
  },
  imgview: {
    backgroundColor: colors.bglightcream,
    borderRadius: 12,
    position: 'relative',
    height: '100%',
  },
  fondimg: {
    position: 'absolute',
    width: '100%',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  textcontain: {
    width: scale(192),
    marginVertical: scaleVertical(38),
    marginRight: halfindent,
    marginLeft: 'auto',
  },
  talktext: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    marginTop: 10,
  },
  reviewSection: {
    marginTop: 30,
  },
  allreview: {
    position: 'relative',
  },
  centerview: {
    width: '100%',
    alignItems: 'center',
    alignSelf: 'center',
    paddingHorizontal: indent,
  },
  reviewtext: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    marginTop: halfindent,
    textAlign: 'center',
    lineHeight: 19,
  },
  clientname: {
    fontWeight: fontWeights.extraBold,
    color: colors.dimGray,
    marginTop: halfindent - 2,
    textAlign: 'center',
  },
  btnview: {
    marginTop: indent + halfindent - 3,
    paddingHorizontal: indent,
    marginBottom: indent + halfindent,
  },
  btntextmain: {
    color: colors.white,
    fontWeight: fontWeights.extraBold,
    marginRight: halfindent - 2,
  },
  btnplan: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: indent,
    borderRadius: 8,
    backgroundColor: colors.primary,

    marginRight: lessIndent,
    ...Platform.select({
      ios: {
        flexGrow: 1,
        paddingHorizontal: 28,
      },
    }),
  },
  btnDemo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: indent,
    borderRadius: 8,
    flex: 0.5,
    marginRight: lessIndent,
    backgroundColor: colors.yellow,
    ...Platform.select({
      ios: {
        flexGrow: 1,
        paddingHorizontal: 30,
        flex: 0,
      },
    }),
  },
  rootScreen: {
    flex: 1,
    backgroundColor: colors.white,
  },
  calnderday: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
    paddingTop: indent,
  },
  bgview: {
    backgroundColor: colors.bggray,
    width: 40,
    height: 40,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  centerCardview: {
    alignItems: 'center',
  },
  numtext: {
    color: colors.dimGray,
    fontWeight: fontWeights.semiBold,
    fontFamily: 'Roboto-Regular',
  },
  dayname: {
    fontWeight: fontWeights.medium,
    color: colors.dimGray,
    marginTop: halfindent / 2,
    textTransform: 'uppercase',
    fontFamily: 'Roboto-Regular',
  },
  bgviewactive: {
    width: 40,
    height: scaleVertical(64),
    backgroundColor: colors.yellow,
    borderRadius: 75,
    paddingVertical: 5,
    paddingHorizontal: 5,
    alignItems: 'center',
  },
  activeday: {
    width: 30,
    height: 30,
    backgroundColor: colors.white,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activedayname: {
    fontWeight: fontWeights.medium,
    color: colors.white,
    marginTop: halfindent + 1,
    textTransform: 'uppercase',
    fontFamily: 'Roboto-Regular',
  },
  dailycard: {
    backgroundColor: colors.bgyellow,
    marginTop: indent,
    borderRadius: 12,
  },
  rowlistItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: indent + halfindent,
  },
  imgScreen: {
    width: scale(105),
    height: scaleVertical(105),
  },
  textlist: {
    width: scale(150),
    marginLeft: 5,
  },
  captext: {
    color: colors.dimGray,
  },
  icon_view: {
    width: 36,
    height: 36,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
    marginLeft: 'auto',
  },
  activitysec: {
    marginTop: indent + halfindent,
  },
  cardlist: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: halfindent / 2,
    margin: -8,
  },
  spacelist: {
    width: '100%',
    maxWidth: '50%',
    minWidth: '50%',
    flex: 1,
    padding: halfindent,
  },
  cardItem: {
    borderRadius: 12,
    alignItems: 'center',
    overflow: 'hidden',
    paddingBottom: 12,
    paddingTop: 6,
  },
  yogimg: {
    width: 98,
    height: 98,
  },
  cardtext: {
    fontWeight: fontWeights.extraBold,
    color: colors.dimGray,
    marginTop: halfindent - 2,
    width: 160,
    textAlign: 'center',
  },
  smileicon: {
    marginRight: halfindent - 2,
  },
  textmain: {
    marginTop: indent + halfindent,
  },
  pdgBottm: {
    paddingBottom: indent,
  },
  headtext: {
    color: colors.black,
    fontWeight: fontWeights.extraBold,
  },
  dayview: {
    width: 24,
    height: 24,
    backgroundColor: colors.primary,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: halfindent,
  },
  daytext: {
    fontWeight: fontWeights.semiBold,
    color: colors.white,
  },
  ltext: {
    color: colors.dimGray,
    fontWeight: fontWeights.semiBold,
    marginRight: halfindent - 1,
  },
  btnhead: {
    paddingVertical: 4,
    paddingHorizontal: indent,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  btnheadtext: {
    ...Typography.capsOne,
    color: colors.white,
    fontWeight: fontWeights.semiBold,
  },
  headerIcons: {
    marginRight: lessIndent,
  },
  headerIconsTwo: {
    marginRight: lessIndent,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headTitle: {
    color: colors.black,
    fontWeight: fontWeights.extraBold,
    marginTop: indent + 4,
  },
  capsind: {
    color: colors.dimGray,
    fontWeight: fontWeights.extraBold,
    marginTop: 5,
  },
  FactView: {
    borderWidth: borderWidth,
    borderColor: colors.borderColor,
    borderRadius: 5,
    paddingVertical: halfindent + 2,
    paddingHorizontal: halfindent + 2,
    alignItems: 'center',
    flexDirection: 'row',
    flex: 1,
    width: '100%',
  },
  factText: {
    marginLeft: halfindent + 2,
  },
  factTop: {
    color: colors.dimGray,
    fontWeight: fontWeights.extraBold,
  },
  captionfact: {
    color: colors.dimGray,
    marginTop: halfindent - 3,
  },
  rowlisttwo: {
    marginTop: doubleIndent - 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  userstwo: {
    alignItems: 'center',
    width: '100%',
    maxWidth: '33.33%',
    paddingHorizontal: halfindent,
    marginBottom: indent,
  },
  clientView: {
    marginTop: indent,
    paddingBottom: indent,
  },
  coutryname: {
    color: colors.dimGray,
    textAlign: 'center',
  },
  quotesWrap: {
    backgroundColor: colors.bglightgreen,
    borderRadius: 12,
    position: 'relative',
    paddingBottom: lessIndent,
    marginTop: 50,
  },
  quotesbgImg: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
  },
  quoteImg: {
    width: 80,
    height: 80,
    alignSelf: 'center',
    position: 'absolute',
    top: -30,
  },
  textBox: {
    paddingHorizontal: 48,
    paddingTop: 58,
    paddingBottom: 15,
  },
  tagsStyles: {
    p: {
      textAlign: 'center',
      color: colors.dimGray,
      fontWeight: fontWeights.medium,
      ...Typography.caption,
      margin: 0,
    },
  },
  list: {
    paddingHorizontal: indent,
  },
  //Modal
  ModalPopup: {
    width: WIN_WIDTH - indent * 3,
    height: 'auto',
    backgroundColor: colors.white,
    borderRadius: 4,
  },
  modalWrap: {
    padding: indent,
  },
  coloseIcon: {
    alignSelf: 'flex-end',
  },
  modalImg: {
    width: 167,
    height: 103,
    alignSelf: 'center',
  },
  modalNewCaps: {
    marginTop: doubleIndent - 2,
    marginBottom: halfindent + 2,
  },
  modalHead: {
    textAlign: 'center',
    color: colors.black,
    fontWeight: fontWeights.extraBold,
  },
  capsModal: {
    textAlign: 'center',
    lineHeight: 23,
  },
  modalBtn: {
    marginTop: doubleIndent,
  },
  btnModal: {
    borderRadius: 8,
  },
  rowList: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkCaps: {
    marginLeft: halfindent,
  },
  //card
  freeCardWrap: {
    backgroundColor: colors.bgyellow,
    borderRadius: 12,
    paddingRight: lessIndent,
    overflow: 'hidden',
    marginTop: halfindent - 2,
    marginBottom: halfindent - 2,
  },
  freeCardWrapdemo: {
    backgroundColor: colors.bgyellow,
    borderRadius: 12,
    paddingRight: lessIndent,
    overflow: 'hidden',
    marginTop: indent,
    marginBottom: halfindent - 2,
  },
  startNow: {
    backgroundColor: colors.yellow,
    flexDirection: 'row',
    alignItems: 'center',
    width: 100,
    justifyContent: 'center',
    borderRadius: 4,
    paddingVertical: halfindent - 2,
    marginTop: halfindent,
  },
  freeRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  freeImg: {
    width: 85,
    height: 120,
  },
  textFreeWrap: {
    paddingLeft: halfindent,
    flexWrap: 'wrap',
  },
  freeTextHead: {
    color: colors.black,
    fontWeight: fontWeights.extraBold,
  },
  daycaps: {
    color: colors.dimGray,
  },
  startBtn: {
    color: colors.white,
    fontWeight: fontWeights.extraBold,
  },
  iconRight: {
    marginTop: 2,
    marginLeft: 4,
  },
  tag: {
    position: 'absolute',
    width: 75,
    height: 26,
    bottom: 0,
    right: 0,
  },
  demo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
    backgroundColor: colors.bglightcream,
    paddingVertical: 10,
    borderRadius: 8,
  },
  demoText: {
    color: colors.red,
    fontFamily: 'Roboto-Medium',
    fontWeight: fontWeights.extraBold,
  },
  purchasecard: {
    paddingHorizontal: indent,
  },
  footBtnRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: -lessIndent,
  },
  footerBox: {
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
  quotes: {
    paddingHorizontal: indent,
    marginTop: 15,
    paddingBottom: lessIndent,
  },
  husbandquotesWrap: {
    backgroundColor: colors.bgsky,
    borderRadius: 12,
    position: 'relative',
    paddingBottom: lessIndent,
    marginTop: 50,
  },
  cardheading: {
    fontWeight: fontWeights.extraBold,
    color: colors.dimGray,
    marginTop: halfindent,
    textAlign: 'center',
  },
  textcontent: {
    textAlign: 'center',
    color: colors.dimGray,
    fontWeight: fontWeights.medium,
    ...Typography.capsOne,
    marginTop: 12,
  },
  cardtopright: {
    position: 'absolute',
    right: 0,
  },
  cardbottomleft: {
    position: 'absolute',
    bottom: 0,
    left: 0,
  },
});
